//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAdminPannel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public long messageid { get; set; }
        public Nullable<long> fk_fromuser { get; set; }
        public Nullable<long> fk_touser { get; set; }
        public string messagecontant { get; set; }
        public string messagesubject { get; set; }
        public Nullable<byte> isactive { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
    }
}
