//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAdminPannel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_packagemaster
    {
        public long packageid { get; set; }
        public string packagename { get; set; }
        public string packagedescription { get; set; }
        public Nullable<int> durationdays { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<byte> isactive { get; set; }
        public string entryby { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
    }
}
