//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAdminPannel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cartdetails
    {
        public long cartdetailsid { get; set; }
        public Nullable<long> fk_cartid { get; set; }
        public Nullable<long> fk_productid { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> discountpercentage { get; set; }
        public Nullable<decimal> discontamount { get; set; }
    }
}
