//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAdminPannel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public long cartid { get; set; }
        public string cartcode { get; set; }
        public Nullable<long> transactionid { get; set; }
        public Nullable<long> fk_userid { get; set; }
        public Nullable<decimal> totalprice { get; set; }
        public Nullable<decimal> discoutamount { get; set; }
        public Nullable<int> discountpercentage { get; set; }
        public Nullable<byte> isactive { get; set; }
    }
}
