//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAdminPannel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public long paymentid { get; set; }
        public Nullable<long> fk_cartid { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string transactioncode { get; set; }
        public Nullable<byte> transactionstatus { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<long> fk_userid { get; set; }
        public string paymenttype { get; set; }
    }
}
